baseURL: https://r4fun.netlify.app/
languageCode: en-us
title: Mediumish
theme: mediumish-gohugo-theme
summaryLength: 25
copyright: Thiyanga S. Talagala and Priyanga D. Talagala - All rights reserved
enableEmoji: yes
publishDir: docs
params:
  author:
    description: xx
    name: Data Analysis with R
    thumbnail: /images/author.png
  description: the clean blog!
  index:
    alertbar: no
    mdtext: |
      R is a free software environment for statistical computing and graphics. The R programming language is widely used in academia and industry for data mining and data analysis. R is also among the top-10 most popular and powerful programming languages. R offers a variety of methods for statistical modelling, computing and data visualization. In this workshop you will learn about the tidyverse R packages, a powerful set of tools for making stunning data visualizations and a useful way of statistical modelling.
    picture: /images/author.png
    subtitle: Dr Thiyanga S. Talagala and Dr Priyanga D. Talagala
    title: Data Analysis with R
  logo: /images/logo.png
  social:
    github: <username>
    instagram: <username>
    linkedin: <username>
    medium: <username>
    twitter: <username>
    xing: <username>
menu:
  main:
    - identifier: blog
      name: Workshop Materials
      url: /blog
      weight: 100
    - identifier: about
      name: Home
      url: /
      weight: 200
    - identifier: imprint
      name: Workshops
      url: /static/imprint
      weight: 200
