baseURL: https://r4fun.netlify.app/
languageCode: en-us
title: Data Analysis with R
theme: mediumish-gohugo-theme
summaryLength: 15
copyright: Thiyanga S. Talagala and Priyanga D. Talagala - All rights reserved
enableEmoji: yes
publishDir: docs
params:
  author:
    description: Dr. Thiyanga S. Talagala and Dr Priyanga D. Talagala
    name: Data Analysis with R
    thumbnail: /images/author1.jpeg
  description: 
  index:
    alertbar: no
    mdtext: |
      This workshop website is developed and maintained by [Dr. Thiyanga S. Talagala](https://thiyanga.netlify.app/) and [Dr. Priyanga D. Talagala](https://prital.netlify.app/) 
      
      This hands-on workshop aims to equip participants with the fundamentals of programming in R and give them skills needed to apply data analysis approaches to their research questions. The workshop will be taught in a similar style to Data Carpentry workshops. Data Carpentry’s mission is to train researchers in the core data skills for efficient, shareable, and reproducible research practices.
   
      
      ##### Licence
      
      ![](/images/license.png)
      
      This work is licensed under a [Creative Commons Attribution 4.0 International License](https://creativecommons.org/licenses/by/4.0/).
    picture: /images/author1.jpeg
    subtitle: 
    title: Data Analysis with R Programming Language
  logo: /images/logo.png
menu:
  main:
    - identifier: blog
      name: Workshop Materials
      url: /blog
      weight: 200
    - identifier: about
      name: Home
      url: /static/author
      weight: 100
    - identifier: imprint
      name: Workshops
      url: /static/imprint
      weight: 200
    - identifier: imprint2
      name: Code of Conduct
      url: /static/imprint2
      weight: 300
    - identifier: imprint3
      name: Additional Resources
      url: /static/imprint3
      weight: 400
