baseURL: https://example.com/
languageCode: en-us
title: Mediumish
theme: mediumish-gohugo-theme
summaryLength: 25
copyright: John Doe - All rights reserved
enableEmoji: yes
publishDir: docs
params:
  author:
    description: Creator of this blog.
    name: John Doe
    thumbnail: /images/author.png
  description: the clean blog!
  index:
    alertbar: no
    mdtext: |
      Currently trying to get this blog running, still don't know what the blog will be about!\
      **This textblock is a demonstration of the mdtext-param.**\
      ### This is a markdown heading
    picture: /images/author.png
    subtitle: I'm a unique placeholder. Working here and there!
    title: John Doe
  logo: /images/logo.png
  social:
    github: <username>
    instagram: <username>
    linkedin: <username>
    medium: <username>
    twitter: <username>
    xing: <username>
menu:
  main:
    - identifier: blog
      name: Blog
      url: /blog
      weight: 100
    - identifier: about
      name: About Me
      url: /
      weight: 200
    - identifier: imprint
      name: Imprint
      url: /static/imprint
      weight: 200
