baseURL: https://r4fun.netlify.app/
languageCode: en-us
title: Data Analysis with R
theme: mediumish-gohugo-theme
summaryLength: 15
copyright: Thiyanga S. Talagala and Priyanga D. Talagala - All rights reserved
enableEmoji: yes
publishDir: docs
params:
  author:
    description: Dr. Thiyanga S. Talagala and Dr Priyanga D. Talagala
    name: Data Analysis with R
    thumbnail: /images/author.png
  description: 
  index:
    alertbar: no
    mdtext: |
      [Dr Thiyanga S. Talagala](https://thiyanga.netlify.app/) and [Dr Priyanga D. Talagala](https://prital.netlify.app/) 
      
      R is a free software environment for statistical computing and graphics. The R programming language is widely used in academia and industry for data mining and data analysis. R is also among the top-10 most popular and powerful programming languages. R offers a variety of methods for statistical modelling, computing and data visualization. In this workshop you will learn about the tidyverse R packages, a powerful set of tools for making stunning data visualizations and a useful way of statistical modelling.
    picture: /images/author.png
    subtitle: 
    title: Data Analysis with R Programming 
  logo: /images/logo.png
menu:
  main:
    - identifier: blog
      name: Workshop Materials
      url: /blog
      weight: 200
    - identifier: about
      name: Home
      url: /
      weight: 100
    - identifier: imprint
      name: Workshops
      url: /static/imprint
      weight: 200
    - identifier: imprint2
      name: Code of Conduct
      url: /static/imprint2
      weight: 300
    - identifier: imprint3
      name: Additional Resources
      url: /static/imprint3
      weight: 400
