baseURL = ""
languageCode = "en-us"
theme = "SimpleIntro"
title = "Theme Demo"
publishDir = "public"

[params]
    mainbg = "https://picsum.photos/1920/1080"
    name = "John Doe"
    mainTitle = "Simple-intro"
    mainText = "Just simple intro theme for hugo"

[menus]
    [[menu.main]]
        identifier = "about"
        name = "About"
        url = "#about"
    [[menu.main]]
        identifier = "skills"
        name = "Skills"
        url = "#skills"
    [[menu.main]]
        identifier = "projects"
        name = "Projects"
        url = "#projects"